const steps = 16;
const initialCellState = { triggered: false, activated: false };
const lineMap = [
  "SY9",
  "SY8",
  "SY7",
  "FS",
  "EF",
  "CS",
  "BF",
  "SY2",
  "SY1",
  "OH",
  "CH",
  "CP",
  "BD",
];
const initialState = [
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
  new Array(16).fill(initialCellState),
];

// const initialState = [
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
//   [
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//     { triggered: false, activated: false },
//   ],
// ]
export { steps, lineMap, initialState };
