const steps = 16;
const initialCellState = { triggered: false, activated: false };
const lineMap = ["BD", "CP", "CH", "OH", "SY1", "SY2", "SY3"];
const initialState = [
  [
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
  ],
  [
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
  ],
  [
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
  ],
  [
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
  ],
  [
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
  ],
  [
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
  ],
  [
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
    { triggered: false, activated: false },
  ],
];
export { steps, lineMap, initialState, initialCellState };
